
COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="silver")

AS
SELECT
  CountryID,
  CountryName,
  FormalName,
  IsoAlpha3Code
FROM (
  SELECT
    *,
    row_number() OVER (PARTITION BY CountryID ORDER BY _ingested_at DESC) AS rn
  FROM wwi_bronze.application_countries
) x
WHERE rn = 1;
