
COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="silver")
AS
SELECT
  CityID,
  CityName,
  StateProvinceID
FROM (
  SELECT
    *,
    row_number() OVER (PARTITION BY CityID ORDER BY _ingested_at DESC) AS rn
  FROM wwi_bronze.application_cities
) x
WHERE rn = 1;
