COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="gold")
AS
SELECT
  p.StockItemID,
  p.StockItemName,
  p.Brand,
  p.Size,
  p.UnitPrice,
  p.TaxRate,
  s.SupplierName
FROM wwi_silver.dim_product p
LEFT JOIN wwi_silver.dim_supplier s
  ON p.SupplierID = s.SupplierID;
