COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="gold")
AS
WITH dates AS (
  SELECT explode(sequence(to_date('2010-01-01'), to_date('2030-12-31'), interval 1 day)) AS DateKey
)
SELECT
  DateKey,
  year(DateKey)  AS [Year],
  quarter(DateKey) AS [Quarter],
  month(DateKey) AS [Month],
  date_format(DateKey, 'MMMM') AS MonthName,
  day(DateKey)   AS [Day],
  date_format(DateKey, 'EEEE') AS DayName,
  weekofyear(DateKey) AS WeekOfYear
FROM dates;