COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="silver")
AS
SELECT
  OrderID,
  CustomerID,
  SalespersonPersonID,
  to_date(OrderDate, 'yyyy-MM-dd') AS OrderDate,
  to_date(ExpectedDeliveryDate, 'yyyy-MM-dd') AS ExpectedDeliveryDate,
  CustomerPurchaseOrderNumber,
  CASE WHEN lower(IsUndersupplyBackordered) IN ('1','true','yes','y') THEN true ELSE false END AS IsUndersupplyBackordered,
  Comments,
  MAX(_ingested_at) AS _last_ingested_at
FROM wwi_bronze.sales_orders
WHERE OrderID IS NOT NULL
GROUP BY
  OrderID, CustomerID, SalespersonPersonID,
  to_date(OrderDate, 'yyyy-MM-dd'),
  to_date(ExpectedDeliveryDate, 'yyyy-MM-dd'),
  CustomerPurchaseOrderNumber,
  CASE WHEN lower(IsUndersupplyBackordered) IN ('1','true','yes','y') THEN true ELSE false END,
  Comments;