
COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="silver")
AS
SELECT
  InvoiceLineID,
  InvoiceID,
  StockItemID,
  COALESCE(Quantity, 0) AS Quantity,
  COALESCE(UnitPrice, CAST(0.00 AS DECIMAL(18,2))) AS UnitPrice,
  COALESCE(TaxRate, CAST(0.0000 AS DECIMAL(9,4))) AS TaxRate,
  COALESCE(LineProfit, CAST(0.00 AS DECIMAL(18,2))) AS LineProfit,
  MAX(_ingested_at) AS _last_ingested_at
FROM wwi_bronze.sales_invoice_lines
WHERE InvoiceLineID IS NOT NULL
GROUP BY
  InvoiceLineID,
  InvoiceID,
  StockItemID,
  Quantity,
  UnitPrice,
  TaxRate,
  LineProfit;
