
COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="silver")
AS
SELECT
  StockItemID,
  StockItemName,
  SupplierID,
  Brand,
  Size,
  UnitPrice,
  TaxRate,
  TypicalWeightPerUnit
FROM (
  SELECT
    *,
    row_number() OVER (PARTITION BY StockItemID ORDER BY _ingested_at DESC) AS rn
  FROM wwi_bronze.warehouse_stock_items
) x
WHERE rn = 1;
