
COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="silver")


AS
SELECT
  SupplierID,
  SupplierName,
  SupplierCategoryID,
  PrimaryContactPersonID,
  DeliveryCityID
FROM (
  SELECT
    *,
    row_number() OVER (PARTITION BY SupplierID ORDER BY _ingested_at DESC) AS rn
  FROM wwi_bronze.purchasing_suppliers
) x
WHERE rn = 1;
