COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="gold")
AS 
SELECT
  c.CustomerID,
  c.CustomerName,
  c.CustomerCategoryID,
  c.CreditLimit,
  c.AccountOpenedDate,
  dc.CityName          AS DeliveryCityName
FROM wwi_silver.dim_customer c
LEFT JOIN wwi_silver.dim_city dc
  ON c.DeliveryCityID = dc.CityID

