
COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="gold")
AS
SELECT
  il.InvoiceLineID,
  i.InvoiceID,
  i.InvoiceDate              AS InvoiceDateKey,
  i.CustomerID,
  i.BillToCustomerID,
  i.OrderID,

  il.StockItemID,
  il.Quantity,
  il.UnitPrice,
  il.TaxRate,

  -- Measures
  (il.Quantity * il.UnitPrice)                                      AS GrossAmount,
  (il.Quantity * il.UnitPrice) * (il.TaxRate / 100.0)               AS TaxAmount,
  (il.Quantity * il.UnitPrice) * (1 + (il.TaxRate / 100.0))         AS NetAmount,

  -- Optional measure if WWI extract includes it (you added it in Silver)
  il.LineProfit                                                     AS ProfitAmount
FROM wwi_silver.sales_invoices i
JOIN wwi_silver.sales_invoice_lines il
  ON i.InvoiceID = il.InvoiceID;
