COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="gold")
AS
SELECT
  ol.OrderLineID,
  o.OrderID,
  o.OrderDate                           AS OrderDateKey,
  o.ExpectedDeliveryDate                AS ExpectedDeliveryDateKey,
  o.CustomerID,
  ol.StockItemID,
  ol.Quantity,
  ol.UnitPrice,
  ol.TaxRate,
  (ol.Quantity * ol.UnitPrice)          AS GrossAmount,
  (ol.Quantity * ol.UnitPrice) * (ol.TaxRate / 100.0) AS TaxAmount,
  (ol.Quantity * ol.UnitPrice) * (1 + (ol.TaxRate / 100.0)) AS NetAmount
FROM wwi_bronze.sales_order_lines ol
JOIN wwi_silver.sales_orders o
  ON ol.OrderID = o.OrderID;
