
COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="silver")

AS
SELECT
  CustomerID,
  trim(CustomerName) AS CustomerName,
  BillToCustomerID,
  CustomerCategoryID,
  PrimaryContactPersonID,
  DeliveryCityID,
  PostalCityID,
  CreditLimit,
  to_date(AccountOpenedDate, 'yyyy-MM-dd') AS AccountOpenedDate,
  current_timestamp() AS _conformed_at
FROM (
  SELECT
    *,
    row_number() OVER (PARTITION BY CustomerID ORDER BY _ingested_at DESC) AS rn
  FROM wwi_bronze.sales_customers
) x
WHERE rn = 1;
