
COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="silver")
AS
SELECT
  InvoiceID,
  CustomerID,
  OrderID,
  BillToCustomerID,
  to_date(InvoiceDate, 'yyyy-MM-dd') AS InvoiceDate,
  MAX(_ingested_at) AS _last_ingested_at
FROM wwi_bronze.sales_invoices
WHERE InvoiceID IS NOT NULL
GROUP BY
  InvoiceID,
  CustomerID,
  OrderID,
  BillToCustomerID,
  to_date(InvoiceDate, 'yyyy-MM-dd');
