COMMENT "Generated by GenMLV"
TBLPROPERTIES ("data_zone"="silver")
AS
SELECT
  OrderLineID,
  OrderID,
  StockItemID,
  COALESCE(Quantity, 0) AS Quantity,
  COALESCE(UnitPrice, CAST(0.00 AS DECIMAL(18,2))) AS UnitPrice,
  COALESCE(TaxRate, CAST(0.0000 AS DECIMAL(9,4))) AS TaxRate,
  COALESCE(PickedQuantity, 0) AS PickedQuantity,
  MAX(_ingested_at) AS _last_ingested_at
FROM wwi_bronze.sales_order_lines
WHERE OrderLineID IS NOT NULL
GROUP BY OrderLineID, OrderID, StockItemID, Quantity, UnitPrice, TaxRate, PickedQuantity;
